# Generated by Django 4.0.4 on 2022-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
