# Generated by Django 4.0.4 on 2022-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
